services:

  flink-jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icestream-flink-jobmanager
    hostname: flink-jobmanager
    restart: unless-stopped

    ports:
      - "8081:8081"
      - "6123:6123"

    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      JOB_MANAGER_RPC_PORT: 6123
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 2

      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.rpc.port: 6123
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
        state.backend: hashmap
        state.backend.async: false
        taskmanager.memory.process.size: 1g
        jobmanager.memory.process.size: 1g

    networks:
      - icestream-network

    volumes:
      - /opt/flink/usrlib
      - ./lib/flink-connector-kafka-3.0.2-1.18.jar:/opt/flink/lib/flink-connector-kafka-3.0.2-1.18.jar:ro
      - ./lib/iceberg-flink-runtime-1.18-1.6.1.jar:/opt/flink/lib/iceberg-flink-runtime-1.18-1.6.1.jar:rolib/flink-connector-kafka-3.0.2-1.18.jar:/opt/flink/lib/flink-connector-kafka-3.0.2-1.18.jar:ro

    command: jobmanager

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:8081/overview | grep -q 'Running' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  flink-taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icestream-flink-taskmanager
    hostname: flink-taskmanager
    restart: unless-stopped

    depends_on:
      - flink-jobmanager

    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      JOB_MANAGER_RPC_PORT: 6123
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 2

      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.rpc.port: 6123
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.process.size: 1g

    networks:
      - icestream-network

    volumes:
      - /opt/flink/usrlib
      - ./lib/flink-connector-kafka-3.0.2-1.18.jar:/opt/flink/lib/flink-connector-kafka-3.0.2-1.18.jar:ro
      - ./lib/iceberg-flink-runtime-1.18-1.6.1.jar:/opt/flink/lib/iceberg-flink-runtime-1.18-1.6.1.jar:ro
    command: taskmanager

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://flink-jobmanager:8081/taskmanagers | grep -q 'flink-taskmanager' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


networks:
  icestream-network:
    name: icestream-network
    external: true