import React, {useEffect, useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { ReactFlow, Background, Controls, Handle, Position } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { AreaChart, Area, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, AlertTriangle, Database, Play, Power, RotateCcw, Send, Wifi, X } from 'lucide-react';
import './styles.css';

const API = 'http://localhost:8000';
const sample = {order_id:'ORD-1024', user_id:'usr_48a9', amount:249.99, tax:18};
const initial = {running:true, circuit_open:false, kafka_connected:false,total_orders:0,total_revenue:0,avg_order_value:0,error_rate:0,dlq_count:0,clean:[],dlq:[],events:[]};
function PipelineNode({data}) { return <div className={'pipeline-node '+data.state}><Handle type="target" position={Position.Left}/><div className="node-icon">{data.icon}</div><div><b>{data.label}</b><small>{data.detail}</small></div><span className="dot"/><Handle type="source" position={Position.Right}/>{data.dlq && <Handle type="source" position={Position.Bottom} id="dlq"/>}</div> }
const nodeTypes={pipeline:PipelineNode};
function App(){
 const [status,setStatus]=useState(initial), [url,setUrl]=useState(''), [json,setJson]=useState(JSON.stringify(sample,null,2)), [tab,setTab]=useState('stream'), [message,setMessage]=useState('');
 const refresh=()=>fetch(API+'/status').then(r=>r.json()).then(setStatus).catch(()=>{});
 useEffect(()=>{refresh(); const ws=new WebSocket('ws://localhost:8000/ws'); ws.onmessage=e=>{let x=JSON.parse(e.data); if(x.status)setStatus(x.status)}; const id=setInterval(refresh,5000); return()=>{ws.close();clearInterval(id)}},[]);
 const control=async(a)=>{const r=await fetch(`${API}/control/${a}`,{method:'POST'});setStatus(await r.json())};
 const ingest=async()=>{try {let body=url?{url}:{data:JSON.parse(json)};let r=await fetch(API+'/external-ingest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('Request rejected');setMessage(url?'Polling external source every 5 seconds.':'Event accepted into orders.');setTimeout(()=>setMessage(''),3500)}catch{setMessage('Please enter valid JSON or a valid endpoint.')}};
 const nodes=useMemo(()=>[{id:'p',type:'pipeline',position:{x:0,y:70},data:{label:'Producer',detail:'Incoming events',icon:<Send size={17}/>,state:status.running?'healthy':'warning'}},{id:'k',type:'pipeline',position:{x:230,y:70},data:{label:'Kafka',detail:status.kafka_connected?'localhost:9092':'resilient queue',icon:<Wifi size={17}/>,state:status.kafka_connected?'healthy':'warning'}},{id:'f',type:'pipeline',position:{x:460,y:70},data:{label:'Flink Validator',detail:status.circuit_open?'Circuit open':'6 validation rules',icon:<Activity size={17}/>,state:status.circuit_open?'failure':status.error_rate>15?'warning':'healthy',dlq:true}},{id:'i',type:'pipeline',position:{x:700,y:70},data:{label:'Iceberg',detail:'clean-data table',icon:<Database size={17}/>,state:'healthy'}},{id:'d',type:'pipeline',position:{x:510,y:220},data:{label:'DLQ',detail:`${status.dlq_count} bad records`,icon:<AlertTriangle size={17}/>,state:status.dlq_count?'failure':'healthy'}}],[status]);
 const edges=[{id:'a',source:'p',target:'k',animated:true},{id:'b',source:'k',target:'f',animated:true},{id:'c',source:'f',target:'i',animated:true},{id:'d',source:'f',sourceHandle:'dlq',target:'d',targetHandle:null,style:{stroke:'#f05252'}}];
 const chart=status.clean.slice(-20).map((o,i)=>({name:i+1,orders:i+1,revenue:o.amount}));
 return <main><header><div className="brand"><div className="snow">✦</div><span>ICE<span>STREAM</span></span><em>REAL-TIME OBSERVABILITY</em></div><div className="connection"><i className={status.kafka_connected?'online':''}/>{status.kafka_connected?'Kafka connected':'Demo queue active'}</div></header>
 <section className="hero"><div><p className="eyebrow">STREAM INTELLIGENCE</p><h1>See every event.<br/><span>Trust every decision.</span></h1><p className="lead">Observe, validate, and route streaming data with a live control plane.</p></div><div className="hero-stat"><Activity/><b>{status.running?'Pipeline live':'Pipeline paused'}</b><small>{status.circuit_open?'Circuit breaker requires reset':'Validation engine monitoring'}</small></div></section>
 {status.alert&&<div className="alert"><AlertTriangle size={17}/>{status.alert}<X size={16}/></div>}
 <section className="metrics"><Metric label="Clean orders" value={status.total_orders}/><Metric label="Total revenue" value={'$'+Number(status.total_revenue).toLocaleString()}/><Metric label="Avg. order value" value={'$'+status.avg_order_value}/><Metric label="Error rate" value={status.error_rate+'%'} danger={status.error_rate>15}/></section>
 <section className="layout"><div className="panel pipeline"><div className="panel-head"><div><p className="eyebrow">TOPOLOGY</p><h2>Data pipeline</h2></div><span className="legend"><i/> Healthy <i className="warn"/> Warning <i className="bad"/> Failure</span></div><div className="flow"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView fitViewOptions={{padding:.15}} nodesDraggable={false} nodesConnectable={false} elementsSelectable={false}><Background gap={18} color="#263342"/><Controls showInteractive={false}/></ReactFlow></div></div>
 <div className="panel controls"><p className="eyebrow">CONTROL PLANE</p><h2>Pipeline controls</h2><button className="primary" onClick={()=>control('start')}><Play size={16}/> Start pipeline</button><button onClick={()=>control('stop')}><Power size={16}/> Stop pipeline</button><button className="danger" onClick={()=>control('inject-bad')}><AlertTriangle size={16}/> Inject bad data</button><button onClick={()=>control('reset')}><RotateCcw size={16}/> Reset pipeline</button><p className="fine">Circuit breaker trips when invalid events exceed 30% of the last 20 messages.</p></div></section>
 <section className="embed panel"><div><p className="eyebrow">INGESTION GATEWAY</p><h2>Embed your own data stream</h2><p>Connect a website API or webhook source, or send an event directly into the <code>orders</code> Kafka topic.</p></div><div className="embed-form"><input placeholder="https://api.example.com/orders" value={url} onChange={e=>setUrl(e.target.value)}/><textarea value={json} onChange={e=>setJson(e.target.value)} spellCheck="false"/><button className="primary" onClick={ingest}><Send size={16}/> Start streaming</button>{message&&<small>{message}</small>}</div></section>
 <section className="lower"><div className="panel live"><div className="tabs"><button className={tab==='stream'?'active':''} onClick={()=>setTab('stream')}>Live stream <b>{status.events.length}</b></button><button className={tab==='dlq'?'active':''} onClick={()=>setTab('dlq')}>Dead letter queue <b>{status.dlq_count}</b></button></div><div className="event-list">{(tab==='stream'?status.events:status.dlq).slice(0,8).map((e,i)=><div className={'event '+(e.type==='INVALID'?'invalid':'')} key={e.data?e.data._id:i}><span>{e.type==='INVALID'?'INVALID':'VALID'}</span><code>{JSON.stringify(e.data||e)}</code>{e.error&&<small>{e.error}</small>}</div>)}{!(tab==='stream'?status.events:status.dlq).length&&<div className="empty">Waiting for events…</div>}</div></div><div className="panel chart"><p className="eyebrow">CLEAN-DATA VELOCITY</p><h2>Orders per minute</h2><div className="chartbox"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#49d5ae" stopOpacity=".5"/><stop offset="1" stopColor="#49d5ae" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="name" hide/><YAxis hide/><Tooltip/><Area type="monotone" dataKey="orders" stroke="#49d5ae" fill="url(#g)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div></section>
 </main> }
function Metric({label,value,danger}) {return <div className={'metric '+(danger?'metric-danger':'')}><span>{label}</span><b>{value}</b><small>live aggregate</small></div>}; createRoot(document.getElementById('root')).render(<App/>);
